name: Pytest CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create .env file
      working-directory: ./api
      run: |
        echo "DATABASE_URL=postgresql://user:pass@localhost:5432/dbname" >> .env
        echo "OPENAI_API_KEY=API_KEY" >> .env
        echo "POSTGRES_DB=dbname" >> .env
        echo "POSTGRES_USER=user" >> .env
        echo "POSTGRES_PASSWORD=pass" >> .env

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      working-directory: ./api
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests with pytest
      working-directory: ./api
      run: |
        pytest tests.py